AkkaOnCore.WebAPI/Models/ErrorViewModel.cs
namespace AkkaOnCore.WebAPI.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

AkkaOnCore.WebAPI/Controllers/MeetingController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace AkkaOnCore.WebAPI.Controllers
{
	public class MeetingController : Controller
	{
		public IActionResult Index(Guid id)
		{
			ViewBag.MeetingId = id;

			return View();
		}
	}
}

AkkaOnCore.WebAPI/Controllers/MeetingListController.cs
using AkkaOnCore.WebAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AkkaOnCore.WebAPI.Controllers
{
	public class MeetingListController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
		}
	}
}

AkkaOnCore.WebAPI/Views/Meeting/Index.cshtml
@page
@{
	var meetingId = (Guid) ViewBag.MeetingId;
}
	<div id="meeting">
		<h1>{{model.name}}</h1>
		<ul>
			<li v-for="(agendaItem, id) in model.agenda">
				<h3>{{ agendaItem }}</h3>
			</li>
		</ul>
		<div v-if="disconnected" class="error-banner">Disconnected</div>
		<div>
			<input type="text" v-model="newAgendaItem" placeholder="Agenda Item" v-on:keyup.enter="addAgendaItem" v-on:focus="clearError" v-on:keydown="clearError" /><button v-on:click="addAgendaItem">Add</button>
		</div>
		<div v-if="hasError" class="error-banner">{{ errorMessage }}</div>
	</div>

<script src="~/lib/vue/vue.js"></script>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>

<script>
	var app = new Vue({
		el: '#meeting',
		data: {
			newAgendaItem: "",
			disconnected: false,
			errorMessage: "",
			model: {
				name: "",
				agenda: {}
			}
		},
		methods: {
			loadModel() {
				fetch('/api/meeting/@meetingId')
					.then(response => response.json())
					.then(model => this.model = model);
			},
			addAgendaItem() {
				fetch(
					'/api/meeting/@meetingId/addtoagenda',
					{
						method: 'POST',
						headers: { 'Accept': '*/*', 'Content-Type': 'application/json' },
						body: JSON.stringify({ description: this.newAgendaItem })
					}
				).then(response =>
					{
						if (response.ok)
							this.newAgendaItem = "";
						else
							response.text().then(error => this.errorMessage = error);
					}
				).catch(error => this.errorMessage = error);
			},
			clearError() {
				this.errorMessage = null;
			}
		},
		computed: {
			hasError: function() { return !!this.errorMessage; }
		},
		created() {
			this.loadModel();
		}
	});

	var connection = new signalR.HubConnectionBuilder().withUrl("/signalr/meetingHub").build();

	connection.on("OnAgendaItemAdded", (id, description) => Vue.set(app.model.agenda, id, description));

	function start() {
		connection
			.start()
			.then(() => {
				console.info("Connected");
				app.disconnected = false;
				connection
					.invoke("Subscribe", "@meetingId")
					.then(() => console.info("Subscribed"))
					.catch(err => console.error(err.toString()));
			})
			.catch(err => {
				console.error(err.toString());
				setTimeout(() => start(), 1000);
			});
	}

	connection.onclose(() => {
		console.info("Disconnected, retrying...");
		app.disconnected = true;
		start();
	});

	start();
</script>

AkkaOnCore.WebAPI/Views/MeetingList/Index.cshtml
@page
<div id="meetings">
	<ul>
		<li v-for="(meeting, id) in model.meetings">
			<a :href="'/meeting/index/' + id"><h3>{{ meeting.name }} ({{ meeting.agendaItemCount }})</h3></a>
		</li>
	</ul>
	<div v-if="disconnected" class="error-banner">Disconnected</div>
	<div>
		<input type="text" v-model="newMeetingName" placeholder="Meeting Name" v-on:keyup.enter="startMeeting" v-on:focus="clearError" v-on:keydown="clearError"/><button v-on:click="startMeeting">Start</button>
	</div>
	<div v-if="hasError" class="error-banner">{{ errorMessage }}</div>
</div>

<script src="~/lib/vue/vue.js"></script>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>

<script>
	var app = new Vue({
		el: '#meetings',
		data: {
			newMeetingName: "",
			disconnected: true,
			errorMessage: "",
			model: {
				meetings: {}
			}
		},
		methods: {
			loadMeetings() {
				fetch('/api/meetings')
					.then(response => response.json())
					.then(model => this.model = model);
			},
			startMeeting() {
				fetch(
					'/api/meetings',
					{
						method: 'POST',
						headers: { 'Accept': '*/*', 'Content-Type': 'application/json' },
						body: JSON.stringify({ name: this.newMeetingName })
					}
				).then(response =>
					{
						if (response.ok)
							this.newMeetingName = "";
						else
							response.text().then(error => this.errorMessage = error);
					}
				).catch(error => this.errorMessage = error);
			},
			clearError() {
				this.errorMessage = null;
			}
		},
		computed: {
			hasError: function() { return !!this.errorMessage; }
		},
		created() {
			this.loadMeetings();
		}
	});

	var connection = new signalR.HubConnectionBuilder().withUrl("/signalr/meetingsHub").build();

	connection.on("OnMeetingAddedToList", (id, name) => Vue.set(app.model.meetings, id, { name: name, id: id, agendaItemCount: 0 }));
	connection.on("OnMeetingAgendaCountChanged", (id, newCount) => app.model.meetings[id].agendaItemCount = newCount);

	function start() {
		connection
			.start()
			.then(() => {
				console.info("Connected");
				app.disconnected = false;
			})
			.catch(err => {
				console.error(err.toString());
				setTimeout(() => start(), 1000);
			});
	}

	connection.onclose(() => {
		console.info("Disconnected, retrying...");
		app.disconnected = true;
		start();
	});

	start();
</script>

AkkaOnCore.WebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AkkaOnCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
	        <div class="navbar-header">
		        <a asp-area="" asp-controller="MeetingList" asp-action="Index" class="navbar-brand">AkkaOnCore</a>
	        </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - deimors</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>